Feature/setup message logic/arc 1963
andguladzeshio/ChatApp pull request #2
Opened 2022-01-12 07:10 UTC by andguladzeshio

https://spaceneobank.atlassian.net/browse/ARC-1963

2022-01-13 07:12 UTC, giorgiqemoklidze approved these changes

2022-01-21 06:01 UTC, GiorgiMamagulashvili16 approved these changes

2022-01-26 09:24 UTC, AnaRusadze requested changes

2022-01-26 09:24 UTC, AnaRusadze commented on app/src/main/java/com/example/chatapp/MainActivity.kt
> +        val lowerChat = ChatFragment("მზია")
ასე გადაწოდება ცუდი პრაქტიკაა. user class შექმენი, რომელსაც სახელი ექნება და ბულიანი, isCurrentUser მაგალითად.

2022-01-26 09:47 UTC, andguladzeshio commented on app/src/main/java/com/example/chatapp/MainActivity.kt
> +        val lowerChat = ChatFragment("მზია")
isCurrentUser ცვლადი აღარ დამჭირდა დანარჩენი done

2022-01-26 13:54 UTC, merged